# Generated by Django 3.1.3 on 2020-11-09 03:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_name', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=32)),
                ('item_type', models.CharField(blank=True, max_length=10)),
                ('enhancements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=4)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.character')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CO', 'Completed')], max_length=2)),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userA', to='backend.character')),
                ('userAtoUserB', models.ManyToManyField(related_name='fromAtoB', to='backend.Item')),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userB', to='backend.character')),
                ('userBtoUserA', models.ManyToManyField(related_name='fromBtoA', to='backend.Item')),
            ],
        ),
    ]
